export const ERROR_DUPLICATE_USER = 'Пользователь с таким email уже существует'
export const NOT_FOUND_USER = 'Пользователь с таким email и паролем не найден'
export const ERROR_NOT_FOUND_USER_BY_ID = 'Пользователь не найден'
export const ERROR_FORBIDDEN = 'У вас нет доступа для просмотра записи'
export const ENTITY_NOT_FOUND = 'Сущность не найдена'
